using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PauseMenu : MonoBehaviour
{
    public bool IsPaused = false;
    public static PauseMenu instance;
    
    //public GameObject Win;

    public GameObject pauseMenuUi;

    private void Awake()
    {
        if (instance == null)
        {
            instance = this;
        }
    }
    
    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            if (IsPaused == true)
            {
                Resume();
            }
            else if (IsPaused == false)
            {
                Pause();
            }

        }
    }
    void Pause()
    {
        pauseMenuUi.SetActive(true);
        Time.timeScale = 0f;
        IsPaused = true;
    }
    public void Resume()
    {
        pauseMenuUi.SetActive(false);
        
        Time.timeScale = 1f;
        IsPaused = false;
    }
}
